"""
Task 3: first implementation generated by the LLM (Claude) from the prompt in
README.md, kept as the Task 3 record.  Two changes were made before
execution (marked  # CHANGE 1 / # CHANGE 2 and explained in README.md).

Design: 2 inputs -> 2 hidden units (tanh) -> 1 output logit
        loss = BCEWithLogitsLoss (sigmoid + binary cross-entropy, combined)
        full-batch Adam, 3000 steps, fixed seed

Run:
    python xor_first_implementation.py
"""

import torch
import torch.nn as nn

torch.manual_seed(0)                              # reproducibility

# The four XOR examples: (x1, x2) -> y
X = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
y = torch.tensor([[0.], [1.], [1.], [0.]])

# 2-2-1 network; random initialisation is PyTorch's default for nn.Linear
model = nn.Sequential(
    nn.Linear(2, 2),     # W1: 2x2, b1: 2
    nn.Tanh(),           # nonlinear hidden activation
    nn.Linear(2, 1),     # W2: 1x2, b2: 1   -> output LOGIT (no sigmoid here)
)
loss_fn = nn.BCEWithLogitsLoss()                  # applies the sigmoid internally
optimiser = torch.optim.Adam(model.parameters(), lr=0.05)

with torch.no_grad():                             # CHANGE 1: record initial loss
    initial_loss = loss_fn(model(X), y).item()

for step in range(3000):
    optimiser.zero_grad()                         # clear old gradients
    logits = model(X)                             # FORWARD PASS
    loss = loss_fn(logits, y)                     # SCALAR LOSS (mean over 4 examples)
    loss.backward()                               # REVERSE-MODE AD (backprop)
    if step == 0:                                 # CHANGE 2: keep an EARLY gradient
        first_grad = model[0].weight.grad.clone()
    optimiser.step()                              # PARAMETERS UPDATED

with torch.no_grad():
    probs = torch.sigmoid(model(X))
    final_loss = loss_fn(model(X), y).item()

print(f"initial loss : {initial_loss:.4f}")
print(f"final loss   : {final_loss:.6f}")
for x, p, t in zip(X.tolist(), probs.squeeze(1).tolist(), y.squeeze(1).tolist()):
    print(f"x={x}  P(y=1)={p:.4f}  label={int(p > 0.5)}  target={int(t)}")
print("all 4 correct:", bool(((probs > 0.5).float() == y).all()))
print("dL/dW1 at step 0:\n", first_grad)
print("dL/dW1 at the last step:\n", model[0].weight.grad)
